apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: qqq-services
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32080
      targetPort: 8080
      name: "http"  # Istio требует явного указания протокола при определенных настройках
  selector:
    app: echoserver

